<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-JJ546MA" failures="3" tests="3" name="Default test(failed)" time="0.114" errors="0" timestamp="2022-02-13T15:14:09 IST">
  <testcase classname="com.testngframework.TestNGFailedTestExecution" name="test4" time="0.021">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.testngframework.TestNGFailedTestExecution.test4(TestNGFailedTestExecution.java:30)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test4 -->
  <testcase classname="com.testngframework.TestNGFailedTestExecution" name="test2" time="0.003">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.testngframework.TestNGFailedTestExecution.test2(TestNGFailedTestExecution.java:18)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test2 -->
  <testcase classname="com.testngframework.TestNGFailedTestExecution" name="test5" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at com.testngframework.TestNGFailedTestExecution.test5(TestNGFailedTestExecution.java:36)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test5 -->
  <testcase classname="com.testngframework.TestNGFailedTestExecution" name="test3" time="0.0">
    <ignored/>
  </testcase> <!-- test3 -->
  <testcase classname="com.testngframework.TestNGFailedTestExecution" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
</testsuite> <!-- Default test(failed) -->
